#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="petsunited")]
	public partial class PetUniteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PetUniteDataContext() : 
				base(global::SendMail.Properties.Settings.Default.petsunitedConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PetUniteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PetUniteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PetUniteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PetUniteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetTemplate")]
		public ISingleResult<sp_GetTemplateResult> sp_GetTemplate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> templateid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), templateid);
			return ((ISingleResult<sp_GetTemplateResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_GetTemplateResult
	{
		
		private string _TemplateText;
		
		public sp_GetTemplateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateText", DbType="VarChar(MAX)")]
		public string TemplateText
		{
			get
			{
				return this._TemplateText;
			}
			set
			{
				if ((this._TemplateText != value))
				{
					this._TemplateText = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
