<?xml version="1.0" encoding="utf-8"?><Database Name="petsunited" Class="PetUniteDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=rossouw.database.windows.net;Initial Catalog=petsunited;User ID=danieros;Connect Timeout=60" SettingsObjectName="SendMail.Properties.Settings" SettingsPropertyName="petsunitedConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_GetTemplate" Method="sp_GetTemplate">
    <Parameter Name="templateid" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_GetTemplateResult">
      <Column Name="TemplateText" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>